import AppKit
import CryptoKit

struct ClipboardCapture {
    enum Payload {
        case text(String)
        case image(data: Data, sha256: String, pixelWidth: Int, pixelHeight: Int)
    }

    let payload: Payload
    let sourceAppName: String?
    let sourceBundleID: String?
}

final class ClipboardMonitorService {
    static let shared = ClipboardMonitorService()

    var onCapture: ((ClipboardCapture) -> Void)?

    private let queue = DispatchQueue(label: "rohoswagger.gojo.clipboard-monitor", qos: .utility)
    private var timer: DispatchSourceTimer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    // Markers used by password managers and other apps to flag pasteboard
    // contents that should never be recorded (http://nspasteboard.org).
    private static let ignoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
    private static let maxImageByteCount = 50 * 1024 * 1024

    private init() {}

    func start() {
        guard timer == nil else { return }
        syncChangeCountToCurrentPasteboard()

        let timer = DispatchSource.makeTimerSource(queue: queue)
        timer.schedule(
            deadline: .now() + .milliseconds(250),
            repeating: .milliseconds(250),
            leeway: .milliseconds(75)
        )
        timer.setEventHandler { [weak self] in
            self?.pollPasteboard()
        }
        self.timer = timer
        timer.resume()
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    func syncChangeCountToCurrentPasteboard() {
        queue.sync {
            lastChangeCount = NSPasteboard.general.changeCount
        }
    }

    private func pollPasteboard() {
        let pasteboard = NSPasteboard.general
        let currentChangeCount = pasteboard.changeCount

        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        guard let capture = extractCapture(from: pasteboard) else { return }
        Task { @MainActor [weak self] in
            self?.onCapture?(capture)
        }
    }

    private func extractCapture(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.ignoredPasteboardTypes.contains($0.rawValue) }) else {
            return nil
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication

        // File copies (Finder etc.) also carry image data for image files;
        // treat those as text so the path string is what gets stored.
        let hasFileURL = types.contains(.fileURL)
        if !hasFileURL, let imagePayload = extractImagePayload(from: pasteboard) {
            return ClipboardCapture(
                payload: imagePayload,
                sourceAppName: sourceApp?.localizedName,
                sourceBundleID: sourceApp?.bundleIdentifier
            )
        }

        guard let text = pasteboard.string(forType: .string),
              !text.isEmpty else {
            return nil
        }

        return ClipboardCapture(
            payload: .text(text),
            sourceAppName: sourceApp?.localizedName,
            sourceBundleID: sourceApp?.bundleIdentifier
        )
    }

    private func extractImagePayload(from pasteboard: NSPasteboard) -> ClipboardCapture.Payload? {
        let pngData: Data?
        if let png = pasteboard.data(forType: .png) {
            pngData = png
        } else if let tiff = pasteboard.data(forType: .tiff) {
            pngData = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        } else {
            pngData = nil
        }

        guard let data = pngData,
              !data.isEmpty,
              data.count <= Self.maxImageByteCount,
              let rep = NSBitmapImageRep(data: data),
              rep.pixelsWide > 0, rep.pixelsHigh > 0 else {
            return nil
        }

        let digest = SHA256.hash(data: data)
        let sha256 = digest.map { String(format: "%02x", $0) }.joined()
        return .image(data: data, sha256: sha256, pixelWidth: rep.pixelsWide, pixelHeight: rep.pixelsHigh)
    }
}
