import AppKit
import CryptoKit

struct ClipboardCapture {
    enum Payload {
        case text(String)
        case image(data: Data, sha256: String, pixelWidth: Int, pixelHeight: Int)
    }

    let payload: Payload
    let sourceAppName: String?
    let sourceBundleID: String?
}

final class ClipboardMonitorService {
    static let shared = ClipboardMonitorService()

    var onCapture: ((ClipboardCapture) -> Void)?

    private let queue = DispatchQueue(label: "rohoswagger.gojo.clipboard-monitor", qos: .utility)
    private var timer: DispatchSourceTimer?

    // Guarded by stateLock, not the poll queue: the poll handler can spend
    // seconds converting a large image, and the main actor must be able to
    // sync the change count without waiting behind it.
    private let stateLock = NSLock()
    private var lastChangeCount = NSPasteboard.general.changeCount

    // Markers used by password managers and other apps to flag pasteboard
    // contents that should never be recorded (http://nspasteboard.org).
    private static let ignoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
    private static let maxImageByteCount = 50 * 1024 * 1024

    private init() {}

    func start() {
        guard timer == nil else { return }
        syncChangeCountToCurrentPasteboard()

        let timer = DispatchSource.makeTimerSource(queue: queue)
        timer.schedule(
            deadline: .now() + .milliseconds(250),
            repeating: .milliseconds(250),
            leeway: .milliseconds(75)
        )
        timer.setEventHandler { [weak self] in
            self?.pollPasteboard()
        }
        self.timer = timer
        timer.resume()
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    func syncChangeCountToCurrentPasteboard() {
        let current = NSPasteboard.general.changeCount
        stateLock.lock()
        lastChangeCount = current
        stateLock.unlock()
    }

    private func pollPasteboard() {
        let pasteboard = NSPasteboard.general
        let currentChangeCount = pasteboard.changeCount

        stateLock.lock()
        let changed = currentChangeCount != lastChangeCount
        lastChangeCount = currentChangeCount
        stateLock.unlock()
        guard changed else { return }

        guard let capture = extractCapture(from: pasteboard) else { return }
        Task { @MainActor [weak self] in
            self?.onCapture?(capture)
        }
    }

    private func extractCapture(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: { Self.ignoredPasteboardTypes.contains($0.rawValue) }) else {
            return nil
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        let text = pasteboard.string(forType: .string)

        // Many apps publish image data alongside real text (Excel cell ranges,
        // Keynote/PowerPoint objects, rich Word content) — those must stay
        // text so history remains searchable and copy-back pastes text.
        // A lone URL string next to image data is browser "Copy Image";
        // keep the image there. File copies (Finder) stay text via the path
        // string since their image flavor is just a preview.
        let hasFileURL = types.contains(.fileURL)
        let hasMeaningfulText = text.map { !$0.isEmpty && !Self.isSingleURL($0) } ?? false
        if !hasFileURL, !hasMeaningfulText,
           let imagePayload = extractImagePayload(from: pasteboard) {
            return ClipboardCapture(
                payload: imagePayload,
                sourceAppName: sourceApp?.localizedName,
                sourceBundleID: sourceApp?.bundleIdentifier
            )
        }

        guard let text, !text.isEmpty else { return nil }

        return ClipboardCapture(
            payload: .text(text),
            sourceAppName: sourceApp?.localizedName,
            sourceBundleID: sourceApp?.bundleIdentifier
        )
    }

    private static func isSingleURL(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty,
              trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let url = URL(string: trimmed),
              let scheme = url.scheme?.lowercased() else {
            return false
        }
        return ["http", "https", "file", "data"].contains(scheme)
    }

    private func extractImagePayload(from pasteboard: NSPasteboard) -> ClipboardCapture.Payload? {
        let pngData: Data?
        if let png = pasteboard.data(forType: .png) {
            pngData = png
        } else if let tiff = pasteboard.data(forType: .tiff) {
            pngData = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        } else {
            pngData = nil
        }

        guard let data = pngData,
              !data.isEmpty,
              data.count <= Self.maxImageByteCount,
              let rep = NSBitmapImageRep(data: data),
              rep.pixelsWide > 0, rep.pixelsHigh > 0 else {
            return nil
        }

        let digest = SHA256.hash(data: data)
        let sha256 = digest.map { String(format: "%02x", $0) }.joined()
        return .image(data: data, sha256: sha256, pixelWidth: rep.pixelsWide, pixelHeight: rep.pixelsHigh)
    }
}
